# Generated by Django 5.1.5 on 2025-01-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('text', models.TextField(verbose_name='Описание курса')),
                ('author', models.CharField(max_length=200, verbose_name='Автор курса')),
            ],
        ),
    ]
